In [5]:
import torch
x = torch.Tensor([1,1])
print(x)
print(x.data.norm())# norm: L2 distance

tensor([1., 1.])
tensor(1.4142)


In [21]:
x = torch.randn(3, requires_grad=True) # x의 grad가 존재함

y = x * 2
while y.data.norm() < 1000:
    y = y * 2
print(x)

gradients = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(torch.tensor([1,0.1,0.1]))# x.grad 에 곱해질 값들

print(x.grad)

tensor([-0.2069, -0.1361, -1.9054], requires_grad=True)
tensor([1024.0000,  102.4000,  102.4000])
